# Generated by Django 5.2.6 on 2025-09-22 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuarioModel',
            fields=[
                ('rous_id', models.AutoField(primary_key=True, serialize=False)),
                ('rous_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'rol_usuario',
                'ordering': ['rous_id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('usua_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usua_rut', models.CharField(max_length=25, unique=True)),
                ('usua_email', models.EmailField(max_length=200, unique=True)),
                ('usua_pass', models.CharField(max_length=128)),
                ('usua_creado', models.DateTimeField(auto_now_add=True)),
                ('usua_actualizado', models.DateTimeField(blank=True, null=True)),
                ('usua_estado', models.IntegerField(choices=[(0, 'Deshabilitado'), (1, 'Habilitado')], default=1)),
                ('rous_id', models.ForeignKey(db_column='rous_id', on_delete=django.db.models.deletion.PROTECT, to='core_models.rolusuariomodel')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
                'ordering': ['-usua_creado'],
            },
        ),
    ]
