# Generated by Django 5.2.6 on 2025-09-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolusuariomodel',
            table='rol_usuarios',
        ),
        migrations.AlterModelTable(
            name='usuariomodel',
            table='Usuarios',
        ),
    ]
