# Generated by Django 5.2.6 on 2025-09-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionTokenModel',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_valor', models.CharField(max_length=36, unique=True)),
                ('token_creado_en', models.DateTimeField(auto_now_add=True)),
                ('token_expira_en', models.DateTimeField()),
                ('token_activo', models.BooleanField(default=True)),
                ('usua_id', models.ForeignKey(db_column='usua_id', on_delete=django.db.models.deletion.CASCADE, to='core_models.usuariomodel')),
            ],
            options={
                'verbose_name': 'Token de Sesión',
                'verbose_name_plural': 'Tokens de Sesión',
                'db_table': 'Sesion_Token',
                'ordering': ['-token_creado_en'],
                'indexes': [models.Index(fields=['token_valor'], name='Sesion_Toke_token_v_852eac_idx'), models.Index(fields=['usua_id', 'token_activo'], name='Sesion_Toke_usua_id_e61ed2_idx')],
            },
        ),
    ]
