# Generated by Django 5.2.6 on 2025-09-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0002_alter_rolusuariomodel_table_alter_usuariomodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuariomodel',
            table='Usuario',
        ),
    ]
