# Generated by Django 5.2.6 on 2025-09-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0003_alter_usuariomodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolusuariomodel',
            table='rol_usuario',
        ),
    ]
