# Generated by Django 5.2.6 on 2025-09-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0004_alter_rolusuariomodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolusuariomodel',
            name='rous_descripcion',
        ),
        migrations.RemoveField(
            model_name='rolusuariomodel',
            name='rous_estado',
        ),
    ]
