# Generated by Django 5.2.6 on 2025-09-25 23:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuarioModel',
            fields=[
                ('rous_id', models.AutoField(primary_key=True, serialize=False)),
                ('rous_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'rol_usuario',
                'ordering': ['rous_id'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('usua_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usua_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('usua_rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('usua_pass', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('usua_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('usua_creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('usua_actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('rous_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='auth_service.rolusuariomodel', verbose_name='Rol de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_valor', models.TextField(unique=True)),
                ('token_expira_en', models.DateTimeField()),
                ('token_creado_en', models.DateTimeField(auto_now_add=True)),
                ('token_activo', models.BooleanField(default=False)),
                ('usua_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='auth_service.usermodel')),
            ],
            options={
                'db_table': 'Session_token',
            },
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['usua_email'], name='Usuario_usua_em_ef33e9_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['usua_rut'], name='Usuario_usua_ru_245df3_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['token_valor'], name='Session_tok_token_v_021e28_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['token_expira_en'], name='Session_tok_token_e_69c3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['usua_id', 'token_activo'], name='Session_tok_usua_id_ef4f1f_idx'),
        ),
    ]
