# Generated by Django 5.2.6 on 2025-09-22 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuarioModel',
            fields=[
                ('rous_id', models.AutoField(primary_key=True, serialize=False)),
                ('rous_nombre', models.CharField(max_length=50, unique=True)),
                ('rous_descripcion', models.TextField(blank=True, null=True)),
                ('rous_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'rol_usuario',
                'ordering': ['rous_id'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rous_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='auth_service.rolusuariomodel', verbose_name='Rol de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_refresh_tokens',
                'indexes': [models.Index(fields=['token'], name='auth_refres_token_02d34a_idx'), models.Index(fields=['expires_at'], name='auth_refres_expires_4ad26b_idx'), models.Index(fields=['user', 'revoked'], name='auth_refres_user_id_67b080_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['email'], name='Usuario_email_411fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['rut'], name='Usuario_rut_823410_idx'),
        ),
    ]
