# Generated by Django 5.2.6 on 2025-09-21 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_refresh_tokens',
                'indexes': [models.Index(fields=['token'], name='auth_refres_token_02d34a_idx'), models.Index(fields=['user', 'revoked'], name='auth_refres_user_id_67b080_idx'), models.Index(fields=['expires_at'], name='auth_refres_expires_4ad26b_idx')],
            },
        ),
    ]
